ARGV = []
TRUE = true
FALSE = false
STDOUT = IO.new
STDIN = IO.new
STDERR = IO.new
ENV = {}
NIL = nil
RUBY_PATCHLEVEL = 95
RUBY_COPYRIGHT = 'ruby - Copyright (C) 1993-2015 Yukihiro Matsumoto'
TOPLEVEL_BINDING = Binding.new
RUBY_VERSION = '2.2.2'
RUBY_PLATFORM = 'x64-mingw32'
